import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

val kotlinVersion: String = "1.9.0"

plugins {
    kotlin("jvm") version "1.9.0"
    kotlin("plugin.serialization") version "1.9.0"
    `java-library`
}

val commonDependencies: DependencyHandlerScope.() -> Unit = {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.2.1")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.1")

    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion")
    implementation("org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-io-core:0.3.0")

    api("com.cave.library:Kotlin-CAVE:0.1")

}

allprojects {
    group = "com.mechanica.engine"
    version = 0.1

    repositories {
        mavenLocal()
        maven {
            url = uri("https://repo.maven.apache.org/maven2")
        }
    }

    apply(plugin = "org.jetbrains.kotlin.jvm")
    dependencies(commonDependencies)
    val compileKotlin: KotlinCompile by tasks
    compileKotlin.kotlinOptions {
        freeCompilerArgs = listOf("-XXLanguage:+InlineClasses")
        languageVersion = "1.9"
        jvmTarget = "1.8"
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}
