/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo

import com.vividsolutions.jts.geom.Coordinate
import com.vividsolutions.jts.geom.GeometryFactory
import display.Game
import display.GameOptions
import graphics.Polygon
import graphics.drawer.Drawer
import models.Model
import state.State
import util.triangulate.EarClipper
import util.units.Vector

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val options = GameOptions()
            .setResolution(1280, 720)
            .setViewPort(height = 10.0)
            .setStartingState { object : State() {
                override fun update(delta: Double) {
                    
                }

                override fun render(draw: Drawer) {
                    draw.green.rectangle(0, 0, 2.0, 2.0)
                }

            } }

    Game.start(options)
    Game.update()
    Game.destroy()
}
